services:
  postgres:
    image: 'postgres:17'
    container_name: coachai-postgres
    environment:
      - POSTGRES_DB=coachai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - '5433:5432' # Maps your machine's port 5433 to the container's Postgres port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data # Saves your data permanently

volumes:
  postgres-data: